### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by Narmical** [phoenix-actions/test-reporting#12]
I have a "junit" type test report produced by Behat. When all the tests pass everything parses fine, however when the tests fail I get this error

```
Error: Cannot read properties of undefined (reading 'split')
```

I am using the java-junit as the test file type

I'm happy to send you the test output file privately

**Comment by Narmical** [comment]
More info: I think its due to the failed tests not having a stacktrace.

**Comment by IanMoroney** [comment]
@Narmical , I've released v7 now which should include a fix for this.
Can you let me know if it works now if the failed tests don't have a stack trace?

Thank you for the bug report!
