### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by ironstas1k** [phoenix-actions/test-reporting#17]
Hi,

I'm trying to parse junit xml reports which were prepared by gtest framework using java-junit format and it's working well for report files which contains successful tests only.
While reporter is trying to parse xml with failed tests - I'm facing ```Error: Cannot read properties of undefined (reading 'split')```

Sometimes our tests are not handling exceptions correctly (because this tests are coming from upstream project) and test case can miss failure message.
```
  <testsuite name="SpellingMenuObserverTest" tests="1" failures="1" disabled="0" errors="0" time="34.336" timestamp="2022-05-24T09:57:08">
    <testcase name="InitMenuWithCorrectWord" status="run" time="34.336" timestamp="2022-05-24T09:56:34" classname="SpellingMenuObserverTest">
      <failure message="" type=""></failure>
    </testcase>
  </testsuite>
```

May I ask you to change current behaviour of parsing such messages if it's missing details. I've tried multiple command line parsers and they are working this way, just to check an assumption that gtest junit xml reports are really compatible with junit parsers.
Thanks in advance!

**Comment by IanMoroney** [comment]
@ironstas1k , this looks very similar to a bug we've already fixed:
https://github.com/phoenix-actions/test-reporting/issues/12
Can you try the [latest version](https://github.com/phoenix-actions/test-reporting/releases) and see if that works for you?

**Comment by IanMoroney** [comment]
Closing for now, but if we need to re-open it again, we can 👍
