### ISSUE TITLE
Unclear documentation 

### ISSUE THREAD

**Issue by sinadenmark** [phoenix-actions/test-reporting#20]
I see in the documentation there is a mention of NUnit as the supported framwork. 

![image](https://user-images.githubusercontent.com/108521167/185917337-5e6423a6-0929-4d1f-a38d-361e77390c53.png)

Since it is on the same line as .NET, I assume it is for dotnet. But why is it that the only dotnet reporter is dotnet-trx? I looked at the code and there is no mention of dotnet-nunit. 

I really need to have this nunit support. Can you clarify how to enable it? (If not, why is it even mentioned in the documentation)

**Comment by IanMoroney** [comment]
Hi @sinadenmark ,

If you use the trx logger:
```
dotnet test --logger trx
```
then the test results can be stored in trx format and parsed by the trx parser. Would this solve your problem?
