### ISSUE TITLE
Applying for GitHub publisher verification for "Test Reporting" Action.

### ISSUE THREAD

**Issue by kenta2097** [phoenix-actions/test-reporting#22]
I’m writing regarding the GH Action [Test Reporting](https://github.com/marketplace/actions/test-reporting)

Our project is starting to migrate the CI/CD to GH Actions and we are interested to use your Actions.
Providing some context, our Security team requires the "Creator Verified by GitHub" badge to start the internal GHA verification process, due to this we are blocked to use unverified Actions.

We would be grateful if you could start the GH Action verification process, as it would help us greatly.

I believe it must improve your impact in the whole GitHub community as a partner organization and also, you are letting us use your actions.

You can find more helpful information in the following articles from GitHub Docs as a good starting point on the process.

[Applying for publisher verification for your organization](https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization)
[About marketplace badges](https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/about-marketplace-badges)

**Comment by kenta2097** [comment]
Hi @IanMoroney @Jake-UFurnish @siegfriedpammer

Could it be possible for you to start the verification process?
We are really interested on using your Action.

Regards

**Comment by IanMoroney** [comment]
@kenta2097 , I've now requested publisher verification 👍 

![image](https://user-images.githubusercontent.com/10791260/200661559-d17a9f2e-a6be-4033-9b30-e74495edfc87.png)

**Comment by kenta2097** [comment]
Hi @IanMoroney 
There's any update regarding the verification?

**Comment by IanMoroney** [comment]
Sadly, no.
As part of the verification process, they require a domain, an email address on that domain, and a functional website on that domain.
That's not something I'm ready to commit to at this point, so it's put a hold on the verification process I'm afraid.
