### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by sunnyoswalcro** [phoenix-actions/test-reporting#24]
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by eshepelyuk** [comment]
Any actions on this plz ?

**Comment by MZole** [comment]
We are also using this workflow in one of our actions in [this action](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/test-dotnet/action.yml#L72). This action is referenced in our projects and it generates the warning for example on [line 116-121](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3315843503/jobs/5476941122) under `Tests` in the jobs. We would also appreciate the migration.

**Comment by IanMoroney** [comment]
Will take a look at this 👍
