### ISSUE TITLE
Test report randomly appears under different workflow

### ISSUE THREAD

**Issue by Piedone** [phoenix-actions/test-reporting#25]
With v8 of the action, we've noticed that sometimes the test reports will appear not under the workflow they were created from, but another workflow that runs in parallel on the same trigger.

The two workflows:

- [`build-and-test`](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/dev/.github/workflows/build-and-test.yml): This runs `test-reporting` for .NET builds. Two jobs run two builds (matrix builds, under Ubuntu and Windows) in parallel. The workflow utilizes an external reusable workflow, and where in the end `test-reporting` is called is [here](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/test-dotnet/action.yml#L72).
- [`validate-pull-request`](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/dev/.github/workflows/validate-pull-request.yml): This doesn't use `test-reporting`.

What we see:

- [This `build-and-test` run](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3289601792) is correct, the test reports appear there. [This is the corresponding `validate-pull-request` run](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3289601799) and this is also correct, no test reports there.
- [This `build-and-test` run](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3289573014) happened 5 minutes before the above one, without changing to the workflows. As you can see, the test reports are not there. They are, instead, under [this is the corresponding `validate-pull-request` run](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3289573012).

This seems to be a bug to me. Note that the two workflows are unrelated apart from having an overlap of triggers.

Before we had the `validate-pull-request` workflow, we noticed test reports randomly missing, which is perhaps the same issue.

**Comment by IanMoroney** [comment]
So, this actually relates to a long-standing github issue, where the requesting run id isn't linked to the check suite id.
It's discussed here in detail:
https://github.com/dorny/test-reporter/issues/67

**Comment by Piedone** [comment]
I see, thanks for explaining. How about then, as a stopgap workaround, do what's mentioned [here](https://github.com/dorny/test-reporter/issues/67#issuecomment-1212969293)? It would even be enough to include the "Check run HTML" link in the run summary.

![image](https://user-images.githubusercontent.com/1976647/200641004-a598ab52-0e32-417a-975c-dfb77bebb8ce.png)

https://github.com/phoenix-actions/test-reporting/pull/21 is about something similar.

**Comment by IanMoroney** [comment]
yep!
merged :)

**Comment by Piedone** [comment]
Thank you!
