### ISSUE TITLE
Incorrect property values 

### ISSUE THREAD

**Issue by YanaSimeonova** [phoenix-actions/test-reporting#29]
The possible values provided for 'list-suites' and 'list-tests' in action.yml are incorrect.
The readme states that the correct values are failed instead of 'only-failed'
https://github.com/phoenix-actions/test-reporting/blob/93ce19fa5882ebe3969ebdb9ee1024b3d29e776f/action.yml#L40
https://github.com/phoenix-actions/test-reporting/blob/93ce19fa5882ebe3969ebdb9ee1024b3d29e776f/action.yml#L47

**Comment by IanMoroney** [comment]
@YanaSimeonova , this looks like a good first issue. Would you like to submit a pull request to correct this?

**Comment by IanMoroney** [comment]
Fixed in https://github.com/phoenix-actions/test-reporting/releases/tag/v11
