### ISSUE TITLE
mochawesome reporter: Error: mocha.passes is not iterable

### ISSUE THREAD

**Issue by AlexBeehave** [phoenix-actions/test-reporting#40]
Hello,

I tried to run the example ./reports/mochawesome/
but the GH action test-reporting fails with the error: Error: mocha.passes is not iterable

Here is the log of the error:
in Run phoenix-actions/test-reporting@v8
Check runs will be created with SHA=2e3f46489bc63dabde89e4c218c27e5dda1961b9
Listing all files tracked by git
Found 66 files tracked by GitHub
Using test report parser 'mocha-json'
Creating test report Report Tests
  Processing test results from integ-tests2/mochawesome-json.json
Error: mocha.passes is not iterable

My workflow is quite simple:
    - name: Checkout Tests
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: npm ci
      working-directory: ./integ-tests2/
    - name: Run Test
      run: npm run test
      working-directory: ./integ-tests2/
    - uses: phoenix-actions/test-reporting@v8
      if: success() || failure()
      id: test-report                     # Set ID reference for step
      with:
        name: Report Tests                  # Name of the check run which will be created
        path: 'integ-tests2/*.json'                     # Path to test results (inside artifact .zip)
        reporter: mocha-json

Any help would be appreciated since I try to get nice reports inside GitHub Actions (i'm working with cypress and mochawesome seems the right reporter)

**Comment by IanMoroney** [comment]
@AlexBeehave , can you update to the latest version and try again to see if you encounter the same issue?
I'll close for now, but will re-open again if you'd like to test again
