### ISSUE TITLE
Public repository separation and matrix jobs

### ISSUE THREAD

**Issue by brianjmurrell** [phoenix-actions/test-reporting#42]
Your [suggestion on having separate workflows for the test and the results posting](https://github.com/phoenix-actions/test-reporting#recommended-setup-for-public-repositories) is interesting.

Do you have any suggestions how that second job (`.github/workflows/test-report.yml`) can be aware of the matrix intersections that uploaded artifacts in a matrix job?

Obviously I could replicate the matrix configuration from the _PR head branch_ (`.github/workflows/ci.yml`) job, but I wonder if you have implemented anything similar and more simple than that matrix configuration replication.

**Comment by IanMoroney** [comment]
One alternative is to try out adding a permission for `checks: write` which may also solve the problem. I had a similar issue in my own workflow, and adding this permission solved the issue for me.
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
