### ISSUE TITLE
Deprecation warning due to Node 16

### ISSUE THREAD

**Issue by Piedone** [phoenix-actions/test-reporting#43]
Node 16 is [now deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Because of this, when using this action, you'll see warnings.

Please update the action to Node 20.

**Comment by Piedone** [comment]
@IanMoroney could you please check this out?

**Comment by IanMoroney** [comment]
Will do, thanks for raising 👍

**Comment by Piedone** [comment]
Awesome, thank you!

**Comment by JohnYoungers** [comment]
I'm guessing this will work as-is by just updating the value to `node20`: https://github.com/phoenix-actions/test-reporting/blob/main/action.yml#L99

**Comment by fin-gordon-cko** [comment]
This would require updating actions from @v2 to @v4
Worth noting in any update that upload-artifact@v4 is not fully backwards compatible with downoad-artifcact@v3 or below
Tried to create a branch for a quick fix but no permissions

**Comment by tonit** [comment]
Would appreciate this one fixed. See existing PR. Waiting for it ;) (if you need more ppl upvoting this.

**Comment by tonit** [comment]
One blocker (i might be wrong) is: downoad-artifcact@v4 is not available for GHEnterprise yet. :/

**Comment by Piedone** [comment]
Any news on this by chance @IanMoroney?

**Comment by IanMoroney** [comment]
Released now:
https://github.com/phoenix-actions/test-reporting/releases/tag/v13

Any issues, raise a new issue 👍

**Comment by Piedone** [comment]
Great, thank you!
